# Generated by Django 5.2 on 2025-05-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('cad_file', models.FileField(blank=True, null=True, upload_to='cad_files/')),
                ('pdf_spl_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('boq_standard', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_method', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Dart.user')),
            ],
        ),
    ]
