# Generated by Django 5.2 on 2025-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('building_a_house', "I'm building a house"), ('quantity_surveyor', "I'm a quantity surveyor"), ('contractor', "I'm a contractor"), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
